language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-yeoman' ]; then cd .. && eval "mv $currentfolder generator-yeoman" && cd generator-yeoman; fi
